language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
  - rustup component add rustfmt
  - rustup target add thumbv7em-none-eabihf
script:
  - cargo build --verbose --all
  - cargo fmt --all -- --check
  - # Run the tests in the FCB generation crate
  - cd imxrt1060-fcb-gen && cargo test --target $(rustup show | grep "Default host" | cut -d' ' -f3) && cd ..
cache: cargo