// Cache configuration
//
// TODO implement this in Rust...?

#include <stdint.h>

#define SCB_CCR (*(volatile uint32_t *)0xE000ED14)
#define SCB_MPU_CTRL (*(volatile uint32_t *)0xE000ED94)
#define SCB_MPU_RBAR (*(volatile uint32_t *)0xE000ED9C)
#define SCB_MPU_RASR (*(volatile uint32_t *)0xE000EDA0)
#define SCB_CACHE_ICIALLU (*(volatile uint32_t *)0xE000EF50)
#define SCB_CCR_IC ((uint32_t)(1 << 17))
#define SCB_CCR_DC ((uint32_t)(1 << 16))

#define SCB_MPU_RBAR_VALID ((uint32_t)(1 << 4))
#define SCB_MPU_RASR_ENABLE ((uint32_t)(1 << 0))
#define SCB_MPU_RASR_XN ((uint32_t)(1 << 28))
#define SCB_MPU_RASR_AP(n) ((uint32_t)(((n)&7) << 24))
#define SCB_MPU_RASR_TEX(n) ((uint32_t)(((n)&7) << 19))
#define SCB_MPU_RASR_C ((uint32_t)(1 << 17))
#define SCB_MPU_RASR_B ((uint32_t)(1 << 16))
#define SCB_MPU_CTRL_ENABLE ((uint32_t)(1 << 0))
#define SCB_MPU_RASR_SIZE(n) ((uint32_t)(((n)&31) << 1))
#define SCB_MPU_RBAR_REGION(n) ((uint32_t)((n)&15))

#define NOEXEC SCB_MPU_RASR_XN
#define READONLY SCB_MPU_RASR_AP(7)
#define READWRITE SCB_MPU_RASR_AP(3)
#define NOACCESS SCB_MPU_RASR_AP(0)
#define MEM_CACHE_WT SCB_MPU_RASR_TEX(0) | SCB_MPU_RASR_C
#define MEM_CACHE_WB SCB_MPU_RASR_TEX(0) | SCB_MPU_RASR_C | SCB_MPU_RASR_B
#define MEM_CACHE_WBWA SCB_MPU_RASR_TEX(1) | SCB_MPU_RASR_C | SCB_MPU_RASR_B
#define MEM_NOCACHE SCB_MPU_RASR_TEX(1)
#define DEV_NOCACHE SCB_MPU_RASR_TEX(2)
#define SIZE_128K (SCB_MPU_RASR_SIZE(16) | SCB_MPU_RASR_ENABLE)
#define SIZE_256K (SCB_MPU_RASR_SIZE(17) | SCB_MPU_RASR_ENABLE)
#define SIZE_512K (SCB_MPU_RASR_SIZE(18) | SCB_MPU_RASR_ENABLE)
#define SIZE_1M (SCB_MPU_RASR_SIZE(19) | SCB_MPU_RASR_ENABLE)
#define SIZE_2M (SCB_MPU_RASR_SIZE(20) | SCB_MPU_RASR_ENABLE)
#define SIZE_4M (SCB_MPU_RASR_SIZE(21) | SCB_MPU_RASR_ENABLE)
#define SIZE_8M (SCB_MPU_RASR_SIZE(22) | SCB_MPU_RASR_ENABLE)
#define SIZE_16M (SCB_MPU_RASR_SIZE(23) | SCB_MPU_RASR_ENABLE)
#define SIZE_32M (SCB_MPU_RASR_SIZE(24) | SCB_MPU_RASR_ENABLE)
#define SIZE_64M (SCB_MPU_RASR_SIZE(25) | SCB_MPU_RASR_ENABLE)
#define REGION(n) (SCB_MPU_RBAR_REGION(n) | SCB_MPU_RBAR_VALID)

void cache_init(void) {
  SCB_MPU_CTRL = 0;

  SCB_MPU_RBAR = 0x00000000 | REGION(0); // ITCM
  SCB_MPU_RASR = MEM_NOCACHE | READWRITE | SIZE_512K;

  SCB_MPU_RBAR = 0x00200000 | REGION(1); // Boot ROM
  SCB_MPU_RASR = MEM_CACHE_WT | READONLY | SIZE_128K;

  SCB_MPU_RBAR = 0x20000000 | REGION(2); // DTCM
  SCB_MPU_RASR = MEM_NOCACHE | READWRITE | NOEXEC | SIZE_512K;

  SCB_MPU_RBAR = 0x20200000 | REGION(3); // RAM (AXI bus)
  SCB_MPU_RASR = MEM_CACHE_WBWA | READWRITE | NOEXEC | SIZE_1M;

  SCB_MPU_RBAR = 0x40000000 | REGION(4); // Peripherals
  SCB_MPU_RASR = DEV_NOCACHE | READWRITE | NOEXEC | SIZE_64M;

  SCB_MPU_RBAR = 0x60000000 | REGION(5); // QSPI Flash
  SCB_MPU_RASR = MEM_CACHE_WBWA | READONLY | SIZE_16M;

  SCB_MPU_CTRL = SCB_MPU_CTRL_ENABLE;

  asm("dsb");
  asm("isb");
  SCB_CACHE_ICIALLU = 0;

  asm("dsb");
  asm("isb");
  SCB_CCR |= (SCB_CCR_IC | SCB_CCR_DC);
}
